### PR TITLE
update contributing.md

### PR DESCRIPTION
**Pull request by khareyash05**
With reference to issue #18 
Added the following -
1. Create an upstream
2. Update the local an forked branch when changes are made in the upstream
3. Squashing the commits into one commit

@vaibhavirohilla741 have a look

### CODE REVIEW

**Review by sharur7 — COMMENTED** [review]
LGTM 👍
Great work! @khareyash05

**Comment by khareyash05** [comment]
@sharur7 Thanx
Is my PR ready to merge?

**Comment by khareyash05** [comment]
@vaibhavirohilla741 could you pls add a level label to the same?

**Comment by khareyash05** [comment]
@vaibhavirohilla741 @sharur7 There is a space between level and 1 in the label thats why this PR isnt being counted
Kindly delete the space between level and 1
Thanx
image

**Pull request merged**
